p1c: init: use aosp recovery script
this patch will fix omni install process
when users make it from stock

Signed-off-by: Humberto Borba <humberos@gmail.com>
Change-Id: I280833041d313aadda510a2ecb650d307a14761f

diff --git a/usr/p1c_initramfs_files/init b/usr/p1c_initramfs_files/init
--- a/usr/p1c_initramfs_files/init
+++ b/usr/p1c_initramfs_files/init
@@ -2,13 +2,13 @@
 export _PATH="$PATH"
 export PATH="/stage1"
 
-date >>/boot.txt
-exec >>/boot.txt 2>&1
-cd /
-mount -t proc proc /proc
-mount -t sysfs sysfs /sys
+busybox cd /
+busybox date >>boot.txt
+exec >>boot.txt 2>&1
+busybox mount -t proc proc /proc
+busybox mount -t sysfs sysfs /sys
 
-rm /init
+busybox rm /init
 
 bml_over_mtd dump boot 72 reservoir 2004 /stage1/boot.bin
 
@@ -22,16 +22,16 @@ NO_EMMC='false'
 BOOTSTRAP='false'
 
 # find the sdcard
-if test `cat /sys/devices/platform/s3c-sdhci.0/mmc_host/mmc0/mmc0:0001/type` != "MMC" ; then
+if busybox test `cat /sys/devices/platform/s3c-sdhci.0/mmc_host/mmc0/mmc0:0001/type` != "MMC" ; then
 	# user has removed the eMMC
 	CACHE='mmcblk0p3'
 	SDCARD='mmcblk0p1'
 	NO_EMMC='true'
 fi
-mount -t vfat /dev/block/"$SDCARD" /sdcard
+busybox mount -t vfat /dev/block/"$SDCARD" /sdcard
 
 # check for bootstrap flag
-if test -e /sdcard/activate_data_on_sdcard ; then
+if busybox test -e /sdcard/activate_data_on_sdcard ; then
 	BOOTSTRAP='true'
 	if ! $NO_EMMC ; then
 		CACHE='mmcblk1p3'
@@ -39,68 +39,78 @@ if test -e /sdcard/activate_data_on_sdcard ; then
 	fi
 fi
 
-mount -t yaffs2 /dev/block/mtdblock2 /system
-mount -t ext4 /dev/block/"$CACHE" /cache
+busybox mount -t yaffs2 /dev/block/mtdblock2 /system
+busybox mount -t ext4 /dev/block/"$CACHE" /cache
 
-if test -e /cache/.startrecovery || grep -q bootmode=2 /proc/cmdline ; then
+if busybox test -e /cache/.startrecovery || busybox grep -q bootmode=2 /proc/cmdline ; then
 	# recovery boot
-	rm -fr /cache/.startrecovery
+	busybox echo 'RECOVERY BOOT' >>boot.txt
+	busybox rm -fr /cache/.startrecovery
 
 	load_image=/stage1/recovery.cpio
 
-	# disable lpm
-	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
-elif ! test -e /system/build.prop ; then
+elif ! busybox test -e /system/build.prop ; then
 	# emergency boot
-        umount /cache
-        make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -a /cache /dev/block/"$CACHE"
-        mount -t ext4 /dev/block/"$CACHE" /cache
-        mkdir /cache/recovery
+	busybox echo "EMERGENCY BOOT" >>boot.txt
+	busybox umount /cache
+	busybox make_ext4fs -b 4096 -g 32768 -i 8192 -I 256 -a /cache /dev/block/"$CACHE"
+	busybox mount -t ext4 /dev/block/"$CACHE" /cache
 
-	UPDATE=$(cat /sdcard/omni.cfg)
+	if ! busybox test -e /cache/recovery ; then
+		busybox mkdir /cache/recovery
+	fi
 
-	if test -e $UPDATE ; then
-		echo "install_zip(\"`echo $UPDATE`\");" > /cache/recovery/extendedcommand
-  	fi
+	if busybox test -e /sdcard/omni.cfg ; then
+		busybox echo "installing: `busybox cat /sdcard/omni.cfg`" >>boot.txt
+		busybox echo "creating recovery command" >>boot.txt
+		busybox touch /cache/recovery/command
+		busybox echo "--update_package=`busybox cat /sdcard/omni.cfg`" > /cache/recovery/command
+	else
+		busybox echo "omni.cfg not found" >>boot.txt
+	fi
 
 	load_image=/stage1/recovery.cpio
 
-	# disable lpm
-	echo 0 > /sys/class/power_supply/battery/charging_mode_booting
+	# umount sdcard
+	busybox umount /sdcard
+
+else
+	# android boot
+	busybox echo "ANDROID BOOT" >>boot.txt
+	busybox echo "loading boot.cpio" >>boot.txt
 fi
 
-umount /cache
-umount /system
-umount /sdcard
-rm -rf /sdcard
+busybox umount /cache
+busybox umount /system
+busybox rm -rf /sdcard
 
-cpio -i < ${load_image}
+busybox cpio -ui < ${load_image}
 
-if grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
+if busybox grep -q 1 /sys/class/power_supply/battery/charging_mode_booting ; then
 	# low power mode
-	cp lpm.rc init.rc
-	rm init.p1c.rc
+	busybox cp lpm.rc init.rc
+	busybox rm init.p1c.rc
 fi
 
 if $BOOTSTRAP ; then
-	sed -i s/mmcblk0p1/"$CACHE"/ /fstab.p1c
-	sed -i s/mmcblk0p2/"$DATA"/ /fstab.p1c
+	busybox sed -i s/mmcblk0p1/"$CACHE"/ /fstab.p1c
+	busybox sed -i s/mmcblk0p2/"$DATA"/ /fstab.p1c
 
-	sed -i s/mmcblk0p1/"$CACHE"/ /etc/recovery.fstab
-	sed -i s/mmcblk0p2/"$DATA"/ /etc/recovery.fstab
-	sed -i s/mmcblk1p1/"$SDCARD"/ /etc/recovery.fstab
+	busybox sed -i s/mmcblk0p1/"$CACHE"/ /etc/recovery.fstab
+	busybox sed -i s/mmcblk0p2/"$DATA"/ /etc/recovery.fstab
+	busybox sed -i s/mmcblk1p1/"$SDCARD"/ /etc/recovery.fstab
 
-	sed -i s/mmcblk0p1/"$CACHE"/ /etc/twrp.fstab
-	sed -i s/mmcblk0p2/"$DATA"/ /etc/twrp.fstab
-	sed -i s/mmcblk1p1/"$SDCARD"/ /etc/twrp.fstab
+	busybox sed -i s/mmcblk0p1/"$CACHE"/ /etc/twrp.fstab
+	busybox sed -i s/mmcblk0p2/"$DATA"/ /etc/twrp.fstab
+	busybox sed -i s/mmcblk1p1/"$SDCARD"/ /etc/twrp.fstab
 fi
 
-umount /sys
-umount /proc
-date >> /boot.txt
+busybox umount /sys
+busybox umount /proc
+busybox date >> /boot.txt
 
-rm -rf /dev/*
-rm -rf /stage1
+busybox rm -rf /dev/*
+busybox rm -rf /stage1
 
 export PATH="${_PATH}"
 
